- hosts: localhost
  connection: local 
  gather_facts: False 
  tasks: 
    - name: Import VPC Variables 
      include_vars: vars/vpc_setup

    - name: Create vprofile VPC 
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes  
        tenancy: default 
        state: "{{state}}"
      register: vpcout  

    - debug:
        var: vpcout 
    
    - name: Create Public Subnet 1 in Zone1 
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone1}}"
        cidr:  "{{PubSub1Cidr}}"
        state: "{{state}}"
        region: "{{region}}"
        map_public: yes
        resource_tags: 
          Name: vprofile-pubsub1
      register: pubsub1_out

    - name: Create Public Subnet 2 in Zone2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone2}}"
        cidr:  "{{PubSub2Cidr}}"
        state: "{{state}}"
        region: "{{region}}"
        map_public: yes
        resource_tags: 
          Name: vprofile-pubsub2
      register: pubsub2_out

    - name: Create Public Subnet 3 in Zone3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone3}}"
        cidr:  "{{PubSub3Cidr}}"
        state: "{{state}}"
        region: "{{region}}"
        map_public: yes
        resource_tags: 
          Name: vprofile-pubsub3
      register: pubsub3_out

    - name: Create Private Subnet 1 in Zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone1}}"
        cidr:  "{{PrivSub1Cidr}}"
        state: "{{state}}"
        region: "{{region}}"
        resource_tags: 
          Name: vprofile-privsub1
      register: privsub1_out

    - name: Create Private Subnet 2 in Zone2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone2}}"
        cidr:  "{{PrivSub2Cidr}}"
        state: "{{state}}"
        region: "{{region}}"
        resource_tags: 
          Name: vprofile-privsub2
      register: privsub2_out

    - name: Create Private Subnet 3 in Zone3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone3}}"
        cidr:  "{{PrivSub3Cidr}}"
        state: "{{state}}"
        region: "{{region}}"
        resource_tags: 
          Name: vprofile-privsub3
      register: privsub3_out

    - name: Internet Gateway Setup 
      ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        resource_tags:
          Name: vprofile_IGW  
        state: "{{state}}" # not required. choices: present;absent. Create or terminate the IGW
        region: "{{region}}"
      register: igw_out 